---
logging:
  level: INFO
  loggers:
    org.example: DEBUG
#
#logging:
#  level: DEBUG
#  loggers:
#    "io.dropwizard": DEBUG
#    "com.yourapp": DEBUG
#  appenders:
#    - type: console
#      threshold: DEBUG
#      logFormat: "%-5level [%d{ISO8601}] [%logger] %message%n%throwable"

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: 1234
  url: jdbc:postgresql://localhost:5432/ecommercedb

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: true


swagger:
  resourcePackage: org.example.resources
  title: My API
  version: 1.0
  schemes:
    - http
  uriPrefix: /
